version: "3"
services:
  bot:
    build: .
    image: sp00tifyb0t
    environment:
      SPOTIFY_USERNAME: ${SPOTIFY_USERNAME}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TOKEN_CACHE: ${TOKEN_CACHE}
